services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Kentucky/Louisville
      - BASE_URL=/ombi
    ports:
      - 3579:3579
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/ombi:/config

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Kentucky/Louisville
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /home_theater_data:/data

  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Kentucky/Louisville
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /home_theater_data:/data
  
  bazarr:
    image: linuxserver/bazarr
    restart: unless-stopped
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Kentucky/Louisville
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /home_theater_data:/data

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Kentucky/Louisville
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config

  vpn:
    image: binhex/arch-qbittorrentvpn
    container_name: qbittorrent
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
      - "8118:8118"
      - "9118:9118"
      - "58946:58946"
      - "9080:9080"
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${OPENVPN_USERNAME}
      - VPN_PASS=${OPENVPN_PASSWORD}
      - VPN_PROV=pia
      - VPN_CLIENT=openvpn
      - ENABLE_STARTUP_SCRIPTS=yes
      - ENABLE_PRIVOXY=yes
      - STRICT_PORT_FORWARD=yes
      - USERSPACE_WIREGUARD=no
      - ENABLE_SOCKS=no
      - LAN_NETWORK=10.0.0.0/16  # Updated LAN network
      - NAME_SERVERS=8.8.8.8,8.8.4.4
      - DEBUG=false
      - WEBUI_PORT=9080
      - UMASK=002
      - PUID=1001  # Updated PUID
      - PGID=1001  # Updated PGID
    volumes:
      - /home_theater_data:/data
      - /docker/appdata/qbittorrent:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Kentucky/Louisville
    ports:
      - 5055:5055
    volumes:
      - /docker/appdata/overseerr:/app/config
    restart: unless-stopped
    user: "1001:1001"
    
  # vpn:
  #   image: binhex/arch-delugevpn:latest
  #   container_name: delugevpn
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - 8112:8112
  #     - 8118:8118
  #     - 58846:58846
  #     - 58946:58946
  #   environment:
  #     - VPN_ENABLED=yes
  #     - VPN_USER=${OPENVPN_USERNAME}
  #     - VPN_PASS=${OPENVPN_PASSWORD}
  #     - VPN_PROV=pia
  #     - VPN_CLIENT=openvpn
  #     - STRICT_PORT_FORWARD=yes
  #     - ENABLE_PRIVOXY=yes
  #     - LAN_NETWORK=10.0.0.0/16
  #     - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
  #     - DELUGE_DAEMON_LOG_LEVEL=info
  #     - DELUGE_WEB_LOG_LEVEL=info
  #     - DELUGE_ENABLE_WEBUI_PASSWORD=yes
  #     - DEBUG=false
  #     - UMASK=000
  #     - PUID=1001
  #     - PGID=1001
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /home_theater_data:/data
  #     - /docker/appdata/delugevpn:/config


