services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    networks:
      - traefik_proxy
    environment:
      - PUID=1002
      - PGID=1002
      # - APP_URL=${HOST_ADDRESS}
      - DB_HOST=${MYSQL_ADDRESS}
      - DB_PORT=3306
      - DB_USER=${MYSQL_USERNAME}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_DATABASE=Bookstack
      - APP_URL=https://docs.${DOMAINNAME_1}
    volumes:
      - /docker/appdata/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.bookstack-rtr.entrypoints=websecure"
      - "traefik.http.routers.bookstack-rtr.rule=Host(`docs.$DOMAINNAME_1`)"
      # HTTP Services
      - "traefik.http.routers.bookstack-rtr.service=bookstack-svc"
      - "traefik.http.services.bookstack-svc.loadbalancer.server.port=80"
      # Middleware
      - "traefik.http.routers.bookstack-rtr.middlewares=chain-authelia@file"

networks:
  traefik_proxy:
    external: true