services:
  omada:
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    container_name: omada_controller
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    network_mode: host
    volumes:
      - /docker/appdata/omada_controller:/opt/tplink/EAPController/data
      - /docker/appdata/omada_controller:/opt/tplink/EAPController/logs
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=America/Kentucky/Louisville
      # - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      # - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8043
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false