services:
  kiwix-serve:
    container_name: kiwix
    ports:
      - 8090:8080
    image: ghcr.io/kiwix/kiwix-serve:latest
    volumes:
      - /docker/appdata/kiwix:/data
    command:
      - '*.zim'